test_that("multiplication works", {
  x1 = rnorm(30,3,2) + 0.1*c(1:30)
  x2 = rbinom(30, 1,0.3)
  x3 = rpois(n = 30, lambda = 4)
  x3[16:30] = x3[16:30] - rpois(n = 15, lambda = 2)
  x4 = rpois(n = 30, lambda = 3)
  y = c(rbinom(5, 1,0.1),rbinom(10, 1,0.25),rbinom(10, 1,0.75),rbinom(5, 1,0.9))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x2), y)), as.vector(glm(y~x1+x2,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x4), y)), as.vector(glm(y~x1+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x3), y)), as.vector(glm(y~x1+x3,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x2,x3), y)), as.vector(glm(y~x2+x3,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x2,x4), y)), as.vector(glm(y~x2+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x3,x4), y)), as.vector(glm(y~x3+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x2,x3), y)), as.vector(glm(y~x1+x2+x3,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x2,x4), y)), as.vector(glm(y~x1+x2+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x2,x3,x4), y)), as.vector(glm(y~x2+x3+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x3,x4), y)), as.vector(glm(y~x1+x3+x4,,family="binomial")$coefficients))
  expect_equal(as.numeric(logistic_regression(cbind(x1,x2,x3,x4), y)), as.vector(glm(y~x1+x2+x3+x4,,family="binomial")$coefficients))
})
